import { doc, query, updateDoc, collection, where, getDocs } from 'firebase/firestore';
import { db } from '../database/config';
import { DeckType } from '../types/deck_type';
import { getUserId } from '../util';


/* function to update new task to firestore */
export const updateDeckService = async (data: DeckType) => {
    const uid = getUserId();
     const deckId = data.id.toString();
    
  const col = collection(db, `/decks/${uid}/deck/`);
  
  const q = query(col, where('id', '==', deckId));

  const docs = await getDocs(q);
//get the autogenerated id for document
  const ref = JSON.stringify(docs.docs[0].id).replaceAll('"', '');
  
  const taskDocRef = doc(db, `/decks/${uid}/deck/${ref}`);
  if (taskDocRef) {
    try {
      const elem = {
        crypt: data.crypt,
        deckType: data.deckType,
        description: data.description,
        library: data.library,
        name:data.name
      }
      const response = await updateDoc(taskDocRef, elem );
      
      console.log('%cData successfully added. ', 'color:green'+response);
    } catch (err) {
        console.log('%cError while saving data', 'color:red');
        console.log(err);
    }
  }
};
